In [1]:
import pandas as pd
import numpy as np

In [2]:
food = pd.read_csv('openfoodfacts.csv', engine = 'python', sep = '\t', on_bad_lines = 'skip')

In [3]:
food.shape

(320767, 162)

In [4]:
food_head = food.head(200)

In [5]:
food_head.describe()

,no_nutriments,additives_n,ingredients_from_palm_oil_n,ingredients_from_palm_oil,ingredients_that_may_be_from_palm_oil_n,ingredients_that_may_be_from_palm_oil,nutrition_grade_uk,energy_100g,energy-from-fat_100g,fat_100g,...,ph_100g,fruits-vegetables-nuts_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
count,0.0,188.000000,188.0,0.0,188.000000,0.0,0.0,181.000000,0.0,152.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,65.000000,65.000000,0.0,0.0
mean,NaN,0.547872,0.0,NaN,0.026596,NaN,NaN,1748.281768,NaN,21.23500,...,NaN,NaN,NaN,NaN,NaN,NaN,10.261538,10.261538,NaN,NaN
std,NaN,1.411506,0.0,NaN,0.241065,NaN,NaN,594.257579,NaN,23.17213,...,NaN,NaN,NaN,NaN,NaN,NaN,7.622493,7.622493,NaN,NaN
min,NaN,0.000000,0.0,NaN,0.000000,NaN,NaN,5.000000,NaN,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,-6.000000,-6.000000,NaN,NaN
25%,NaN,0.000000,0.0,NaN,0.000000,NaN,NaN,1423.000000,NaN,2.48500,...,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,6.000000,NaN,NaN
50%,NaN,0.000000,0.0,NaN,0.000000,NaN,NaN,1582.000000,NaN,12.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,11.000000,NaN,NaN
75%,NaN,0.000000,0.0,NaN,0.000000,NaN,NaN,2092.000000,NaN,35.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,14.000000,NaN,NaN
max,NaN,10.000000,0.0,NaN,3.000000,NaN,NaN,3586.000000,NaN,100.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,30.000000,NaN,NaN

In [6]:
food.dtypes

code                        object
url                         object
creator                     object
created_t                   object
created_datetime            object
                            ...
carbon-footprint_100g      float64
nutrition-score-fr_100g    float64
nutrition-score-uk_100g    float64
glycemic-index_100g        float64
water-hardness_100g        float64
Length: 162, dtype: object

In [7]:
food_head.to_csv('food_head.csv')

In [8]:
food.describe()

,no_nutriments,additives_n,ingredients_from_palm_oil_n,ingredients_from_palm_oil,ingredients_that_may_be_from_palm_oil_n,ingredients_that_may_be_from_palm_oil,nutrition_grade_uk,energy_100g,energy-from-fat_100g,fat_100g,...,ph_100g,fruits-vegetables-nuts_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
count,0.0,248934.000000,248934.000000,0.0,248934.000000,0.0,0.0,2.611080e+05,857.000000,243886.000000,...,49.000000,3036.000000,165.000000,948.000000,0.0,268.000000,221206.000000,221206.000000,0.0,0.0
mean,NaN,1.936047,0.019660,NaN,0.055248,NaN,NaN,1.141908e+03,585.501214,12.730394,...,6.425698,31.458587,15.412121,49.547785,NaN,341.700764,9.165488,9.058000,NaN,NaN
std,NaN,2.502036,0.140526,NaN,0.269210,NaN,NaN,6.447215e+03,712.809943,17.578871,...,2.047841,31.967918,3.753028,18.757932,NaN,425.211439,9.055924,9.183612,NaN,NaN
min,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,8.000000,6.000000,NaN,0.000000,-15.000000,-15.000000,NaN,NaN
25%,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,3.770000e+02,49.400000,0.000000,...,6.300000,0.000000,12.000000,32.000000,NaN,98.750000,1.000000,1.000000,NaN,NaN
50%,NaN,1.000000,0.000000,NaN,0.000000,NaN,NaN,1.100000e+03,300.000000,5.000000,...,7.200000,23.000000,15.000000,50.000000,NaN,195.750000,10.000000,9.000000,NaN,NaN
75%,NaN,3.000000,0.000000,NaN,0.000000,NaN,NaN,1.674000e+03,898.000000,20.000000,...,7.400000,51.000000,15.000000,64.250000,NaN,383.200000,16.000000,16.000000,NaN,NaN
max,NaN,31.000000,2.000000,NaN,6.000000,NaN,NaN,3.251373e+06,3830.000000,714.290000,...,8.400000,100.000000,25.000000,100.000000,NaN,2842.000000,40.000000,40.000000,NaN,NaN

1. Nettoyage :  SÃ©lectionner les variables et individus valides  (4 mÃ©thodes)
    - retenir les variables avec plus 10000 individus avec valeurs .
    - Ã©liminer les individus dont plus 50% valeurs sont manquantes pour les variables
    - Ã©liminer les variables doublons
    - Ã©liminer les individus doublons
    - formaliser les variables

In [9]:
print(food.isnull().sum())

code                           23
url                            23
creator                         2
created_t                       3
created_datetime                9
                            ...
carbon-footprint_100g      320499
nutrition-score-fr_100g     99561
nutrition-score-uk_100g     99561
glycemic-index_100g        320767
water-hardness_100g        320767
Length: 162, dtype: int64

In [49]:
food_var = food.dropna(axis = 1, thresh = 10000)

In [50]:
food_var.describe()

,additives_n,ingredients_from_palm_oil_n,ingredients_that_may_be_from_palm_oil_n,energy_100g,fat_100g,saturated-fat_100g,monounsaturated-fat_100g,polyunsaturated-fat_100g,trans-fat_100g,cholesterol_100g,...,vitamin-a_100g,vitamin-c_100g,vitamin-b1_100g,vitamin-b2_100g,vitamin-pp_100g,potassium_100g,calcium_100g,iron_100g,nutrition-score-fr_100g,nutrition-score-uk_100g
count,248934.000000,248934.000000,248934.000000,2.611080e+05,243886.000000,229550.000000,22823.000000,22859.000000,143296.000000,144086.000000,...,137550.000000,140863.000000,11154.000000,10815.000000,11729.000000,24748.000000,141045.000000,140458.000000,221206.000000,221206.000000
mean,1.936047,0.019660,0.055248,1.141908e+03,12.730394,5.129978,10.425055,6.312493,0.073477,0.020072,...,0.000397,0.023368,0.325574,0.259007,0.020303,0.424635,0.125167,0.003653,9.165488,9.058000
std,2.502036,0.140526,0.269210,6.447215e+03,17.578871,8.014298,17.076167,10.832591,1.540234,0.358067,...,0.073280,2.236483,2.474306,1.277026,0.339262,12.528768,3.318322,0.214411,9.055924,9.183612
min,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,-3.570000,0.000000,...,-0.000340,-0.002100,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000260,-15.000000,-15.000000
25%,0.000000,0.000000,0.000000,3.770000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.004000,0.002720,0.003077,0.107000,0.000000,0.000000,1.000000,1.000000
50%,1.000000,0.000000,0.000000,1.100000e+03,5.000000,1.790000,4.000000,2.220000,0.000000,0.000000,...,0.000000,0.000000,0.012000,0.014167,0.005357,0.180000,0.035000,0.001010,10.000000,9.000000
75%,3.000000,0.000000,0.000000,1.674000e+03,20.000000,7.140000,10.710000,7.140000,0.000000,0.020000,...,0.000107,0.003700,0.402000,0.300000,0.009091,0.341000,0.106000,0.002400,16.000000,16.000000
max,31.000000,2.000000,6.000000,3.251373e+06,714.290000,550.000000,557.140000,98.000000,369.000000,95.238000,...,26.700000,716.981100,161.000000,42.500000,21.428571,1870.370000,694.737000,50.000000,40.000000,40.000000

In [38]:
food_var.head(1000).to_csv('food_var_head.csv')

1. Nettoyage :  SÃ©lectionner les variables et individus valides  (4 mÃ©thodes)
    - Ã©liminer les variables doublons qui termine par '_tags' ou '_fr'

In [52]:
food_var.shape

(320767, 79)

In [54]:
food_var1 = food_var.drop(['created_t'], axis = 1)

In [57]:
food_var1 =food_var1.drop(['last_modified_t'], axis = 1)

In [64]:
test = 'packaging_tags'
test[-5:]

'_tags'

In [65]:
for var in food_var1:
    if (var[-5:] == '_tags') :
        food_var1 = food_var1.drop([var], axis =1)

In [66]:
food_var1.shape

(320767, 64)

In [67]:
for var in food_var1:
    if (var[-3:] == 'url') :
        food_var1 = food_var1.drop([var], axis =1)

In [68]:
food_var1.shape

(320767, 61)

In [69]:
for var in food_var1:
    if (var[-3:] == '_fr' and var[-8:] != 'grade_fr') :
        food_var1 = food_var1.drop([var], axis =1)

In [70]:
food_var1.shape

(320767, 54)

1. Nettoyage :  SÃ©lectionner les variables et individus valides  (4 mÃ©thodes)
    - retenir les variables avec plus 10000 individus avec valeurs .
    - Ã©liminer les variables non signficatives :

In [72]:
food_var2 = food_var1.drop(['created_datetime', 'generic_name','packaging','manufacturing_places',
                           'origins','labels','emb_codes','purchase_places','first_packaging_code_geo',
                           'stores','traces','ingredients_from_palm_oil_n','ingredients_that_may_be_from_palm_oil_n',
                           'additives_n','additives','states'], axis =1)

In [73]:
food_var2.shape

(320767, 38)

In [74]:
food_var2.head(500).to_csv("food_var2.csv")